name: Setup NAPE Tooling
description: Download and install the NAPE CLI binary and install the NAPE Evaluator CLI via pip.

inputs:
  version:
    description: "NAPE CLI version to install"
    required: false
    default: "1.1.0"

runs:
  using: "composite"
  steps:
    - name: Download NAPE CLI
      shell: bash
      run: |
        set -euo pipefail

        NAPE_VERSION="${{ inputs.version }}"
        NAPE_URL="https://repo.napecentral.com/nape-cli/${NAPE_VERSION}/linux-gnu/x86_64/nape"

        echo "Downloading NAPE CLI version ${NAPE_VERSION}"
        curl -fsSL "${NAPE_URL}" -o nape

    - name: Install NAPE CLI
      shell: bash
      run: |
        set -euo pipefail
        chmod +x nape
        sudo mv nape /usr/local/bin/nape

    - name: Install NAPE Evaluator CLI (pip)
      shell: bash
      run: |
        set -euo pipefail

        python3 -m pip install --upgrade pip
        python3 -m pip install nape

        # Ensure user-level pip bin directory is on PATH for later steps in this job
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - name: Verify NAPE CLI installation
      shell: bash
      run: |
        set -euo pipefail
        command -v nape
        nape --help >/dev/null || true

    - name: Verify NAPE Evaluator installation
      shell: bash
      run: |
        set -euo pipefail

        command -v nape-eval

        OUT="$(nape-eval --check-install || true)"
        echo "${OUT}"

        # Verify expected success message is present
        echo "${OUT}" | grep -F "NAPE Evaluator CLI is installed and working." >/dev/null